version: '3.3'
services:
  sqlserver:
    container_name: sql_server
    build: 
        context: .
        dockerfile: ./DataBase/Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: abc12345..
      MSSQL_PID: Express
  api:
    container_name: wep_api
    build:
        context: .
        dockerfile: ./ApiRest/Dockerfile      
    ports:
      - "9090:80"
    volumes:
      - ./server:/app
      - /app/obj/
      - /app/bin/
      - /app/out/
